[build]
    publish = "public/"
    command = "gatsby build"

    [build.environment]
    NODE_VERSION = "22.18.0"

[dev]
    command = "gatsby develop"
    target-port = 8000
    live-reload-port = 8001

    [dev.environment]
    NODE_VERSION = "22.18.0"
