title: Ahmadullah Mirza
subtitle:
  - Web Developer
description: I started my programming career with a blog. From editing my xml
  templates to a full stack software's. I like to code and program in my free
  time as a hobby.
avatar: /img/profile-pic.png
key: homePage
