backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
# publish_mode: editorial_workflow

collections:
  - name: "projects"
    label: "Projects"
    folder: "/content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover", name: "cover", widget: "image" }
      - {
          label: "URL",
          name: "url",
          widget: "string",
          pattern:
            ["https?://(.*)", "The URL must start with http:// or https://"],
          required: false,
        }
      - {
          label: "Source",
          name: "source",
          widget: "string",
          pattern:
            ["https?://(.*)", "The URL must start with http:// or https://"],
          required: false,
        }
      - {
          label: "Tech Stack",
          name: "tech_stack",
          widget: "relation",
          collection: "skills",
          searchFields: ["name"],
          valueField: "name",
          multiple: true,
          displayFields: ["name"],
        }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }

  - name: "testimonials"
    label: "Testimonials"
    folder: "/content/testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }

  - name: "skill_groups"
    label: "Skill Groups"
    folder: "/content/skill_groups"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }

  - name: "skills"
    label: "Skills"
    folder: "/content/skills"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    sortable_fields: ["type"]
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Icon", name: "icon", widget: "image" }
      - {
          label: "Type",
          name: "type",
          widget: "relation",
          collection: "skill_groups",
          searchFields: ["name"],
          valueField: "name",
          displayFields: ["name"],
        }
      - { label: "Level", name: "level", widget: "number", min: 1, max: 100 }

  - name: "Qualifications"
    label: "Qualifications"
    folder: "/content/qualifications"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Institution", name: "institution", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Logo", name: "logo", widget: "image", required: false }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Duration", name: "duration", widget: "string" }
      - {
          label: "type",
          name: "type",
          widget: "select",
          options: ["educational", "professional"],
        }

  - name: "experiences"
    label: "Experiences"
    folder: "/content/experiences"
    create: true
    slug: "{{started}}-{{postion}}-{{institution}}"
    fields:
      - { label: "Postion", name: "postion", widget: "string" }
      - { label: "Institution", name: "institution", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Logo", name: "logo", widget: "image", required: false }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Started", name: "started", widget: "datetime" }
      - { label: "Ended", name: "ended", widget: "datetime", required: false }

  - name: "configurations"
    label: "Configurations"
    files:
      - label: "Site Metadata"
        name: "site_metadata"
        file: "/content/config/site_metadata.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: false,
            }
          - {
              label: "keywords",
              name: "keywords",
              widget: "string",
              required: false,
            }
          - { label: "URL", name: "url", widget: "string", required: false }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Text Logo", name: "text_logo", widget: "string" }
          - {
              label: "key",
              name: "key",
              widget: "string",
              default: "siteMetadata",
            }

      - label: "Hero Section"
        name: "hero_section"
        file: "/content/config/hero_section.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "list",
              field: { label: "Text", name: "text", widget: "string" },
            }
          - { label: "Resume", name: "resume", widget: "string" }
          - { label: "Avatar", name: "avatar", widget: "image" }
          - { label: "key", name: "key", widget: "string", default: "homePage" }

      - label: "About Section"
        name: "about_section"
        file: "/content/config/about_section.md"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Text", name: "text", widget: "markdown" }
          - {
              label: "key",
              name: "key",
              widget: "string",
              default: "aboutPage",
            }

      - label: "Hire Section"
        name: "hire_section"
        file: "/content/config/hire_section.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Button",
              name: "button",
              widget: "object",
              fields:
                [
                  { label: "Text", name: "text", widget: "string" },
                  { label: "Link", name: "link", widget: "string" },
                ],
            }
          - { label: "Image", name: "image", widget: "image" }
          - {
              label: "key",
              name: "key",
              widget: "string",
              default: "hireSection",
            }

      - label: "Contact Info"
        name: "contact_info"
        file: "/content/config/contact_info.md"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
          - {
              label: "key",
              name: "key",
              widget: "string",
              default: "contactInfo",
            }

      - name: "social_media"
        label: "Social Media"
        file: "/content/config/social_media.md"
        fields:
          - { label: "Github", name: "github", widget: "string" }
          - { label: "Linkedin", name: "linkedin", widget: "string" }
          - { label: "Twitter", name: "twitter", widget: "string" }
          - {
              label: "key",
              name: "key",
              widget: "string",
              default: "socialMedia",
            }

      - name: "footer"
        label: "Footer"
        file: "/content/config/footer.md"
        fields:
          - { label: "Text", name: "text", widget: "string" }
          - {
              label: "key",
              name: "key",
              widget: "string",
              default: "footerDetails",
            }
